const path = {

  getNoticeAdviseList: '/wx/noticeAdvise/list',
  getNoticeAdviseById: '/wx/noticeAdvise/get_by_id',
  updateNoticeAdvise: '/wx/noticeAdvise/update',
  createNoticeAdvise: '/wx/noticeAdvise/create',
  deleteNoticeAdvise: '/wx/noticeAdvise/delete',
  getLibraryTypeList: '/wx/libraryType/list',
  getLibraryTypeById: '/wx/libraryType/get_by_id',
  updateLibraryType: '/wx/libraryType/update',
  createLibraryType: '/wx/libraryType/create',
  deleteLibraryType: '/wx/libraryType/delete',
  getSeatStatusList: '/wx/seatStatus/list',
  getSeatStatusById: '/wx/seatStatus/get_by_id',
  updateSeatStatus: '/wx/seatStatus/update',
  createSeatStatus: '/wx/seatStatus/create',
  deleteSeatStatus: '/wx/seatStatus/delete',
  getOrderMangeList: '/wx/orderMange/list',
  getOrderMangeById: '/wx/orderMange/get_by_id',
  updateOrderMange: '/wx/orderMange/update',
  createOrderMange: '/wx/orderMange/create',
  deleteOrderMange: '/wx/orderMange/delete',
  getBooksMangerList: '/wx/booksManger/list',
  getBooksMangerById: '/wx/booksManger/get_by_id',
  updateBooksManger: '/wx/booksManger/update',
  createBooksManger: '/wx/booksManger/create',
  deleteBooksManger: '/wx/booksManger/delete',
  getBookReadList: '/wx/bookRead/list',
  getBookReadById: '/wx/bookRead/get_by_id',
  updateBookRead: '/wx/bookRead/update',
  createBookRead: '/wx/bookRead/create',
  deleteBookRead: '/wx/bookRead/delete'
}
export default path
